nginx:
  build: "nginx"
  restart: always
  ports:
    - "443:443"
  links:
    - registryv1:registryv1
    - registryv2:registryv2
registryv1:
  image: registry
  restart: always
  environment:
    - GUNICORN_OPTS=["--preload"] 
  ports:
    - "127.0.0.1:32794:5000"
  volumes:
    - /registry/v1:/tmp/registry
registryv2:
  image: registry:2
  restart: always
  ports:
    - "127.0.0.1:32795:5000"
  volumes:
    - /registry/v2:/tmp/registry-dev
